/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entities.Staff;
import entities.shared.GymSystem;
import enums.Role;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Johan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFailDial = new javax.swing.JDialog();
        loginFailPanel = new javax.swing.JPanel();
        loginFailLbl = new javax.swing.JLabel();
        loginFailBtn = new javax.swing.JButton();
        loginNameTxt = new javax.swing.JTextField();
        loginPasstxt = new javax.swing.JPasswordField();
        loginNameLbl = new javax.swing.JLabel();
        loginPassLbl = new javax.swing.JLabel();
        loginLoginbtn = new javax.swing.JButton();
        loginTitleLbl = new javax.swing.JLabel();

        loginFailDial.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginFailDial.setTitle("Error");
        loginFailDial.setAlwaysOnTop(true);
        loginFailDial.setAutoRequestFocus(false);
        loginFailDial.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        loginFailDial.setModal(true);
        loginFailDial.setPreferredSize(new java.awt.Dimension(250, 180));
        loginFailDial.setResizable(false);
        loginFailDial.setSize(new java.awt.Dimension(250, 180));
        loginFailDial.setLocationRelativeTo(null);

        loginFailLbl.setText("Incorrect username or password !");

        loginFailBtn.setText("Back");
        loginFailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFailPanelLayout = new javax.swing.GroupLayout(loginFailPanel);
        loginFailPanel.setLayout(loginFailPanelLayout);
        loginFailPanelLayout.setHorizontalGroup(
            loginFailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFailPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(loginFailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFailPanelLayout.createSequentialGroup()
                        .addComponent(loginFailLbl)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFailPanelLayout.createSequentialGroup()
                        .addComponent(loginFailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        loginFailPanelLayout.setVerticalGroup(
            loginFailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFailPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loginFailLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(loginFailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout loginFailDialLayout = new javax.swing.GroupLayout(loginFailDial.getContentPane());
        loginFailDial.getContentPane().setLayout(loginFailDialLayout);
        loginFailDialLayout.setHorizontalGroup(
            loginFailDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginFailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        loginFailDialLayout.setVerticalGroup(
            loginFailDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginFailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGC Management System");

        loginNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNameTxtActionPerformed(evt);
            }
        });

        loginPasstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasstxtActionPerformed(evt);
            }
        });

        loginNameLbl.setText("Username :");

        loginPassLbl.setText("Password :");

        loginLoginbtn.setText("Login");
        loginLoginbtn.setName(""); // NOI18N
        loginLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginLoginbtnActionPerformed(evt);
            }
        });

        loginTitleLbl.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        loginTitleLbl.setText("GYM MANAGEMENT CENTRE SIGN-IN");
        loginTitleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginTitleLbl)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginLoginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginPassLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginPasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(loginTitleLbl)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPassLbl)
                    .addComponent(loginPasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(loginLoginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginNameTxt.getAccessibleContext().setAccessibleName("loginNametxt");
        loginPasstxt.getAccessibleContext().setAccessibleName("loginPasstxt");
        loginNameLbl.getAccessibleContext().setAccessibleName("loginNamelbl");
        loginPassLbl.getAccessibleContext().setAccessibleName("loginPasslbl");
        loginLoginbtn.getAccessibleContext().setAccessibleName("loginLoginbtn");
        loginTitleLbl.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("loginFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginFailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFailBtnActionPerformed
        loginFailDial.setVisible(false);
    }//GEN-LAST:event_loginFailBtnActionPerformed

    private void loginLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLoginbtnActionPerformed
        try {
            String username = loginNameTxt.getText();
            String password = String.valueOf(loginPasstxt.getPassword());
            GymSystem gym = new GymSystem();
            Staff staff = gym.staff.login(username, password);

            if (staff == null) {
                loginFailDial.setVisible(true);

            } else if (staff.role.equals(Role.Manager)) {
                this.setVisible(false);
                new ManagerMainFrame().setVisible(true);

            } else if (staff.role.equals(Role.Trainer)) {
                this.setVisible(false);
                new TrainerMainFrame().setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginLoginbtnActionPerformed

    private void loginPasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasstxtActionPerformed

    }//GEN-LAST:event_loginPasstxtActionPerformed

    private void loginNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNameTxtActionPerformed

    }//GEN-LAST:event_loginNameTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginFailBtn;
    private javax.swing.JDialog loginFailDial;
    private javax.swing.JLabel loginFailLbl;
    private javax.swing.JPanel loginFailPanel;
    private javax.swing.JButton loginLoginbtn;
    private javax.swing.JLabel loginNameLbl;
    private javax.swing.JTextField loginNameTxt;
    private javax.swing.JLabel loginPassLbl;
    private javax.swing.JPasswordField loginPasstxt;
    private javax.swing.JLabel loginTitleLbl;
    // End of variables declaration//GEN-END:variables
}
